tasks:
  - init: |
      docker-compose pull
  - command: |
      docker-compose up

ports:
  - port: 81
    onOpen: open-browser

github:
  prebuilds:
    master: false
    branches: false
    pullRequests: false
    pullRequestsFromForks: false
    addCheck: false
    addComment: false
    addBadge: false