version: '3'

services:
    koillection:
        container_name: koillection
        image: koillection/koillection
        restart: always
        ports:
            - 81:80
        environment:
            - APP_ENV=prod
            - APP_DEBUG=0
            - DB_DRIVER=pdo_pgsql
            - DB_NAME=koillection
            - DB_HOST=postgresql
            - DB_PORT=5432
            - DB_USER=postgres
            - DB_PASSWORD=blb37bGOZGQeBCJB42jy
            - DB_VERSION=14
            - PHP_TZ=Europe/Paris
            - HTTPS_ENABLED=1
        depends_on:
            - postgresql

    postgresql:
        container_name: postgresql
        image: postgres:14
        environment:
            - POSTGRES_DB=koillection
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=blb37bGOZGQeBCJB42jy
            - POSTGRES_HOST_AUTH_METHOD=trust
        ports:
            - 5432:5432
